# Generated by Django 3.0.6 on 2021-06-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigntime',
            name='enddate',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='assigntime',
            name='startdate',
            field=models.DateField(default=''),
        ),
    ]
