# Generated by Django 3.0.6 on 2021-06-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20210628_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntime',
            name='enddate',
            field=models.DateField(default='2021-10-23'),
        ),
        migrations.AlterField(
            model_name='assigntime',
            name='startdate',
            field=models.DateField(default='2021-10-23'),
        ),
    ]
