# Generated by Django 3.0.6 on 2021-06-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20210628_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntime',
            name='enddate',
            field=models.DateField(default='2014-10-23'),
        ),
        migrations.AlterField(
            model_name='assigntime',
            name='startdate',
            field=models.DateField(default='2001-01-01'),
        ),
    ]
