# Generated by Django 3.0.6 on 2021-06-28 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20210628_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntime',
            name='enddate',
            field=models.DateField(default=datetime.date(2012, 10, 3)),
        ),
        migrations.AlterField(
            model_name='assigntime',
            name='startdate',
            field=models.DateField(default=datetime.date(2012, 10, 3)),
        ),
    ]
