# Generated by Django 3.0.6 on 2021-06-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20210628_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntime',
            name='enddate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='assigntime',
            name='startdate',
            field=models.DateField(blank=True),
        ),
    ]
