# Generated by Django 3.0.6 on 2021-06-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20210628_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntime',
            name='enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='assigntime',
            name='startdate',
            field=models.DateField(),
        ),
    ]
