# Generated by Django 3.0.6 on 2021-06-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_auto_20210628_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerange',
            name='end_date',
            field=models.DateField(default='2020-10-23'),
        ),
    ]
