# Generated by Django 3.0.6 on 2021-06-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_auto_20210628_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerange',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendancerange',
            name='start_date',
            field=models.DateField(),
        ),
    ]
